[package]
name = "v8-format"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
integer-encoding = "3.0.2"

[dev-dependencies]
serde_bytes = "0.11"
